const usersArray = [
  {
    id: 1,
    name: "Faith Hoffman",
    age: 30,
    phone: "041-906-2754",
    email: "faith.hoffman@example.com",
    balance: 9234,
    picture: "https://randomuser.me/api/portraits/women/12.jpg",  
  },
  {
    id: 2,
    name: "Tracy McConell",
    age: 27,
    phone: "04-8717-9239",
    email: "tracy.mcconell@example.com",
    balance: 12000,
    picture: "https://randomuser.me/api/portraits/women/31.jpg",
  },
  {
    id: 3,
    name: "Mason Smithers",
    age: 22,
    phone: "013873 95315",
    email: "mason.smithers@example.com",
    balance: 14000,
    picture: "https://randomuser.me/api/portraits/men/40.jpg",
  },
  {
    id: 4,
    name: "Jeremy Lo",
    age: 34,
    phone: "893-194-4584",
    email: "jeremy.lo@example.com",
    balance: 7000,
    picture: "https://randomuser.me/api/portraits/men/92.jpg",
  },
  {
    id: 5,
    name: "Tommy Odland",
    age: 57,
    phone: "87516933",
    email: "tommy.odland@example.com",
    balance: 4300,
    picture: "https://randomuser.me/api/portraits/men/47.jpg",
  },
  {
    id: 6,
    name: "Ann Robertson",
    age: 24,
    phone: "05-8557-4218",
    email: "ann.robertson@example.com",
    balance: 8900,
    picture: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: 7,
    name: "Eva Smith",
    age: 42,
    phone: "791-422-1232",
    email: "eva.smith@example.com",
    balance: 1200,
    picture: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: 8,
    name: "Michael Watkins",
    age: 77,
    phone: "281-953-6576",
    email: "michael.watkins@example.com",
    balance: 6735,
    picture: "https://randomuser.me/api/portraits/men/45.jpg",
  },
  {
    id: 9,
    name: "Jens Sundli",
    age: 33,
    phone: "73326022",
    email: "jens.sundli@example.com",
    balance: 3400,
    picture: "https://randomuser.me/api/portraits/men/37.jpg",
  },
  {
    id: 10,
    name: "Rayna Stolwijk",
    age: 73,
    phone: "176-667-7623",
    email: "rayna.stolwijk@example.com",
    balance: 10000,
    picture: "https://randomuser.me/api/portraits/women/45.jpg",
  },
];

export default usersArray;
